app:
  twitter:
    consumerKey: '%env(TWITTER_CONSUMER_KEY)%'
    consumerSecret: '%env(TWITTER_CONSUMER_SECRET)%'
    oauthToken: '%env(TWITTER_OAUTH_TOKEN)%'
    oauthSecret: '%env(TWITTER_OAUTH_SECRET)%'

  feeds:
    - id: iamcodeguru
      feedUrl: https://iamcode.guru/feed
      name: I Am Code Guru
      author: Bartłomiej Kiełbasa
      twitter: https://twitter.com/kabanek
      facebook: https://www.facebook.com/iamcodeguru/
    - id: laravel-news
      feedUrl: https://feed.laravel-news.com/
      name: Laravel News
      author: Laravel News
    - id: symfony-blog
      feedUrl: https://feeds.feedburner.com/symfony/blog
      name: Symfony Blog
      author: Symfony Blog
    - id: murze-be
      feedUrl: https://murze.be/feed
      name: murze.be
      author: Freek Van der Herten
    - id: fabien-poncier
      feedUrl: http://feeds.fabien.potencier.org/aidedecamp?format=xml
      name: Fabien Potencier
      author: Fabien Potencier
    - id: za-warstwa-abstrakcji
      feedUrl: https://zawarstwaabstrakcji.pl/atom.xml
      author: Norbert Orzechowicz
      name: Za Warstwą Abstrakcji
      twitter: norzechowicz
