homepage:
  path: /
  controller: App\Controller\LatestPostsController::index

rss2:
  path: /feed/rss2
  controller: App\Controller\FeedsController::rss2

edition_show:
  path: /edition/{editionId}
  controller: App\Controller\EditionController::show
